language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mkorneyc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mkorneyc/docker-react npm run test


