language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mkorneyc/docker-react

script:
  - docker run -e CI=true mkorneyc/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-110525979287"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
